### ISSUE TITLE
require('@abandonware/noble') in serial_noble.js

### ISSUE THREAD

**Issue by antlai** [espruino/EspruinoTools#104]
The noble dependency was replaced  with @abandonware/noble by @goodwid commit but the require() in serial_noble.js is still using 'noble' not '@abandonware/noble' and it cannot load it.

It is just one line, but just let me know if you want a pull..

Thanks

**Comment by gfwilliams** [comment]
Thanks! Just fixed this hopefully :) I thought I'd already done it but it seems that was only for EspruinoHub
