### ISSUE TITLE
no console client appier after  

### ISSUE THREAD

**Issue by Maksss2018** [espruino/EspruinoTools#107]
instead of console client connecting process stopping and that all what I can see on display:
 ```
Espruino Command-line Tool 0.1.29
-----------------------------------

Using first port, {"path":"/dev/ttyACM0","usb":[483,5740],"description":"STMicroelectronics"}
Connecting to '/dev/ttyACM0'
user@raspberrypi:~$
```
please help me  solve this problem.

**Comment by gfwilliams** [comment]
I need more information to be able to help you...

* What board are you trying to connect to? 
* What are you running the tools on? 
* What version of node.js?
* What command are you typing to start it?
* What is printed if you add `--verbose` to the command?

**Comment by Maksss2018** [comment]
> 
> 
> I need more information to be able to help you...
> 
>     * What board are you trying to connect to?
> 
>     * What are you running the tools on?
> 
>     * What version of node.js?
> 
>     * What command are you typing to start it?
> 
>     * What is printed if you add `--verbose` to the command?

 * What board are you trying to connect to?  What are you running the tools on?
   I'm using armbian OS, with  board  that   name is : iskra.js uno ;
     * What version of node.js?
- node version 8.0.0.0
     * What command are you typing to start it?
I was trying  to make a work next  commands :
   :~$ espruino -j -t -w /some/home/dir/some.js. 
   :~$ espruino
   :~$  espruino -p /dev/ttyACM0
     * What is printed if you add `--verbose` to the command?
`
Initialising CoreModules
Searching for serial ports...
Noble: getPorts - not initialised
No navigator.bluetooth - Web Bluetooth not enabled
No navigator.serial - Web Serial not enabled
Noble: stateChange -> poweredOff
PORTS:
  /dev/ttyACM0 (STMicroelectronics)
Using first port, {"path":"/dev/ttyACM0","usb":[483,5740],"description":"STMicroelectronics"}
Connecting to '/dev/ttyACM0'
madmax@orangepipc:~$

`

**Comment by gfwilliams** [comment]
Thanks, however I'm not entirely sure what to suggest - this would all seem to look ok.

Maybe you can ask Amperka for support, as it's their board and fork of Espruino.
