### ISSUE TITLE
Module dependancies can be in the wrong order

### ISSUE THREAD

**Issue by ChristiaanWillemsen** [espruino/EspruinoTools#110]
I think It's possible to have the module dependancies in the wrong order. I fixed this by doing the folloing in modules.js

   ```
 var loadProcessedModule = function(module) {
      Promise.all(newPromises).then(function() {
        // add the module to the beginning of our array
        if (Espruino.Config.MODULE_AS_FUNCTION)
          loadedModuleData.push(
            "Modules.addCached(" +
              JSON.stringify(module.name) +
              ",function(){" +
              module.code +
              "});"
          );
        else
          loadedModuleData.push(
            "Modules.addCached(" +
              JSON.stringify(module.name) +
              "," +
              JSON.stringify(module.code) +
              ");"
          );
        // if we needed to load something, wait until we have all promises complete before resolving our promise!

        resolve();
      });
    };
```

**Comment by gfwilliams** [comment]
Do you have example of JS code that'd cause this to break? I haven't heard of any cases where modules weren't found or were in the wrong order so I'm concerned about trying to fix something that isn't broken! :)

**Comment by ChristiaanWillemsen** [comment]
Hi there.

Well, I’ve used typescript to generate the js. In this I have one TS class A using another B, where A is used in the main application file.  This resolves into A first, then B. While the order needs to be the reverse.

I can try to make the code I have a bit more manageable to you can try yourself… Let me come back to you on that.

**Comment by gfwilliams** [comment]
Ahh, ok, got you - just did a simple test with:

```
// foo.js
var a = require("bar");
print(a);
// bar.js
exports = require("baz").bob;
// baz.js
exports.bob=42;
```

and got...

```
Modules.addCached("bar","exports=require('baz').bob;");
Modules.addCached("baz","exports.bob=42;");
var a = require("bar");
print(a);
```

 I just applied your changes - thanks!
