### ISSUE TITLE
Cannot upload firmware to Puck.js

### ISSUE THREAD

**Issue by palortoff** [espruino/EspruinoTools#113]
When the Puck.js is in bootloader mode EspruinoTools cannot connect to the Puck.js to upload the firmware.

Obviously it does not find it under the name `puck.js xxxx`, but it also does not work with `-d 'DfuTarg'` or `-p <device address>` or without a port or device option.

I am running EspruinoTools under Linux Debian buster with bluez 5.50

**Comment by MaBecker** [comment]
please use this howto http://www.espruino.com/Puck.js#firmware-updates

Hint: those questions get much quicker  response on the forum
http://forum.espruino.com/

**Comment by palortoff** [comment]
Thanks for your quick reply. I am aware of other methods to update the firmware to the Puck.js

There are reasons not to use an Android/iOS device.
As EspruinoTools has the option to upload the firmware I think this is the right place for this issue.

**Comment by MaBecker** [comment]
Oh, afaik it is not possible to run firmware updates via WebIDE like it is possible for Pico.
There is a conversation about this in the forum, have a look http://forum.espruino.com/conversations/340193/

**Comment by gfwilliams** [comment]
Hi - as @MaBecker says unfortunately CLI-based firmware update isn't supported in EspruinoTools at the moment.

If you need to use CLI to do it, it's easiest just to use https://www.npmjs.com/package/web-bluetooth-dfu
