### ISSUE TITLE
connects but gets stuck (unlike the Web Serial in the ide)

### ISSUE THREAD

**Issue by opichals** [espruino/EspruinoTools#117]
So after the https://github.com/espruino/EspruinoTools/commit/431c9b9f6095c174c9a6f9fabdfa639009e30025 fix it gets connected but then fails on communication.

It doesn't receive the board info and then blocks any keyboard input (except for Ctrl+C which allows me to exit - as seen in the log below).

The same board, computer (MacOS) and wiring (same USB port) work through Web Serial after enabling the flag suggested in https://github.com/espruino/EspruinoWebIDE/issues/219#issuecomment-584532489.

```
$ npx espruino -b 11520 --no-ble -v
...

Searching for serial ports...
Noble: getPorts - disabled
No navigator.bluetooth - Web Bluetooth not enabled
No navigator.serial - Web Serial not enabled
PORTS:
  /dev/tty.usbserial-14310
  /dev/tty.Bluetooth-Incoming-Port
Using first port, {"path":"/dev/tty.usbserial-14310","usb":[1,7523]}
Connecting to '/dev/tty.usbserial-14310'
Connected Ok
Got ""
No Prompt found, got undefined - issuing Ctrl-C to try and break out
Splitting for Ctrl-C, delay 250
Still no prompt - issuing another Ctrl-C
Splitting for Ctrl-C, delay 250
Sending...
---> "\u0010print(\"<\",\"<<\",JSON.stringify(process.env),\">>\",\">\")\n"
Sent
Receiving...
No result found for "process.env" - just got ""

Unable to retrieve board information.
Connection Error?
Connected
Splitting for Ctrl-C, delay 250

Press Ctrl-C again to exit
>Splitting for Ctrl-C, delay 250

Done
```

**Comment by gfwilliams** [comment]
If that's the actual command you used then the baud rate is likely wrong? Not that it matters for fully USB devices but if it's an ESPXX you'll need 115200

**Comment by opichals** [comment]
Crap! I am sorry! You are right. Thank you!
