### ISSUE TITLE
fileSaveDialog changes binary

### ISSUE THREAD

**Issue by notEvil** [espruino/EspruinoTools#135]
Hi,

when I download a binary file in the Chrome web IDE, the target files content doesn't match the source. When I view the source file in the IDE it shows correctly. So I tracked down the issue and found that when `fileSaveDialog` puts `data` into a `Blob`, it gets reinterpreted (a 10 character string suddenly had Blob length 17). When I changed the part to behave like the non-Chrome part with

```
          var rawdata = new Uint8Array(data.length);
          for (var i=0;i<data.length;i++) rawdata[i]=data.charCodeAt(i);
          var blob = new Blob([rawdata.buffer],{ type: "text/plain"} );
```

it worked.

**Comment by gfwilliams** [comment]
Thanks for this! So you're saying specifically to change this line? https://github.com/espruino/EspruinoTools/blob/master/core/utils.js#L592

I guess probably pull the common Blob code right to the top of the function?

**Comment by notEvil** [comment]
Yes, I reproduced the issue with `var st=require('Storage');st.erase('t');st.write('t','\1A\x9D\xC2\xC2\x88\xCB\0F\0');` (source 10bytes, downloaded 15bytes). And it only appears in the Chrome app, not in Chrome web.

I'm not familiar with js enough to suggest a more lightweight fix than this.

**Comment by gfwilliams** [comment]
Thanks! Just added a fix
