### ISSUE TITLE
[Feature Request]Syntax Highlighting

### ISSUE THREAD

**Issue by Ronin0000** [espruino/EspruinoTools#137]
Is there syntax highlighting in the emulator? If there is it does not work for me.

**Comment by gfwilliams** [comment]
Do you have a screenshot? There's definitely highlighting for me...

![image](https://user-images.githubusercontent.com/754445/131803888-bef7a612-f619-425f-b19b-3ceb679dc106.png)

If you mean the left-hand side of the window then no, there's no highlighting as it's basically just a serial console direct to the device

**Comment by Ronin0000** [comment]
Thanks for replying, now it  is working my setting for this setting "JavaScript Editor Theme"  was not on default and there was no syntax highlighting. I changed it back to default and now its working.

**Comment by Ronin0000** [comment]
> Great - thanks! Do you think you could have changed that setting? I haven't known of anyone else that syntax highlighting didn't appear as standard for...

Yes i am fairly sure I changed that setting.
