### ISSUE TITLE
Save on Send option?

### ISSUE THREAD

**Issue by RobertSmart** [espruino/EspruinoTools#139]
Hi,

Is there a way to enable a save on send function through the cmd line args?

I noticed there was an option in the job file for save on send which might be useable, but I also upload files to storage and can't see this option in the job file anywhere?

Thanks,

Rob

**Comment by gfwilliams** [comment]
There are some examples in the README (https://github.com/espruino/EspruinoTools) like:

```
# Write mycode.js to the first Bangle.js device found as a Storage file named app.js
espruino -d Bangle.js mycode.js --storage app.js:-
```

But I'm not sure if you can specify that from the job file yet

**Comment by RobertSmart** [comment]
Hi,

Thanks for the reply. Will it automatically run app.js on startup? Am I right in assuming in this instance you don't need to use the onInit function, as the whole file will be read from flash and executed? 

 Thanks again!

**Comment by gfwilliams** [comment]
You need to use `--storage .bootcde:-` for it to run at startup.

If you're doing that then you can just do `--config SAVE_ON_SEND=1`. See `espruino --listconfigs` for more info. That one *is* available in the job file.

>  in this instance you don't need to use the onInit function, as the whole file will be read from flash and executed?

That's correct, yes.
