### ISSUE TITLE
local modules are not found during Command-line Tool uploads

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoTools#140]
Want to upload  code from project folder as used with the chrome WebIDE via Espruino Command-line Tool 0.1.38

```txt
espruino -p "f6-70-dd-1b-5a-a0"  project/mycode.js
Espruino Command-line Tool 0.1.38
-----------------------------------

Connecting to 'f6-70-dd-1b-5a-a0'
--] <- Serial1
Connected
********************************************************************
* No list of built-in modules found. If you get 'Module not found' *
* messages for built-in modules you may want to connect to a board *
* with '-p devicePath' or use '--board BOARDNAME'                  *
********************************************************************
Module MYMODULE not found
```

How to tell the Command-line Tool to use the module from the local module folder?

**Comment by MaBecker** [comment]
What about  a `"MODULE_PATH" additional to `MODULE_URL`?

https://github.com/espruino/EspruinoTools/blob/d0d5b1fe1efbac035c3cce12e6ab46bd0673d3d7/configDefaults.json#L29

**Comment by MaBecker** [comment]
Or add  project path?

**Comment by MaBecker** [comment]
ok, next time better read about all the detail/notes and than ask questions.

This section completely solve the request:

MODULE_URL accepts a pipe delimited (|) list of URLS, including local servers and absolute or relative paths based on the code file. For example, "../../modules|http://localhost:8080/modules|http://www.espruino.com/modules" will first look in the module folder located two folders up from the code, then query the localhost server, and then look in the Espruino repository.

**Comment by gfwilliams** [comment]
By default it also looks in a folder called `modules` I believe
