### ISSUE TITLE
Remove unicode.js

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoTools#142]
... or at least make it switchable, default off.

Causing nothing but trouble since it's creation.

http://forum.espruino.com/conversations/367900/#comment16220079

I'd be interested to hear if anyone is actually using this? It seems the *only* use case is when `print`ing non-latin characters to the console. For everything else it breaks perfectly ok code.

**Comment by GermanWarez** [comment]
Is it still in the code, couldn't find it - maybe close the issue?

**Comment by gfwilliams** [comment]
https://github.com/espruino/EspruinoTools/blob/master/plugins/unicode.js

**Comment by gfwilliams** [comment]
Looks like it's now disabled by default, so we could close this I guess
