### ISSUE TITLE
which version of node to use?

### ISSUE THREAD

**Issue by davidmoshal** [espruino/EspruinoTools#15]
Currently not possible to install:  

`npm install -g espruino`

Node version 4 or 5 clearly don't work.

With version 0.12 you get this error, i.e: serial port wants 0.10 or less:

`npm WARN engine serialport@1.2.5: wanted: {"node":"0.10.x"} (current: {"node":"0.12.8","npm":"2.14.9"})`

However, if you run with 0.10 then you get this error:

`npm WARN engine escodegen@1.7.1: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.40","npm":"1.4.28"})`

i.e: escodegen needs node 12.0 or larger!

So, we need a node version x, where: x is <= 0.10 and x is >= 0.12 ??

**Comment by gfwilliams** [comment]
Yay, NPM strikes again. I use v0.10.37 - the one that came installed with Ubuntu.

Although looking at what you've got there is seems as if it shouldn't work, but I just ran `npm install -g espruino` here and it works fine.

Do you think that changing the dependency on serialport from `~1.2.5` to `>=1.2.5` would help you out? I guess you could try checking it out yourself, changing it in `package.json` and doing `npm install -g .`

... but looking at it, those are two warnings. Has it actually errored? Because if not it has probably installed and runs just fine.

**Comment by gfwilliams** [comment]
Did you have any luck with this?

**Comment by davidmoshal** [comment]
Gordon: Both of the the above warnings were fatal.

However, interestingly, I just tried again, using the current version of node, and it worked, albeit with a non-fatal warning.

```
$ node --version
v5.1.0

$ npm install -g espruino
... lot's of output, then this last line:
npm WARN EBUNDLEOVERRIDE Replacing bundled espruino > serialport > node-pre-gyp-github with new installed version
```

and this works just fine:
```
espruino -p /dev/tty.usbmodem1411
```

Dang your software and hardware are awesome. We are about to start using it for a STEAM physical computing course. Just ordered a Pico, will decide between it and the Espruino, plan is to give one to each kid.

Your offering is so much more robust than that of other vendors, (pretty sure I've tried out every embedded system out there), including those from vendors with very deep pockets. 
Amazing work. Thank you, and thanks for checking in on this.

Dave

**Comment by davidmoshal** [comment]
I think I found the docs:  
Espruino/targets/esp8266/docs ?

**Comment by gfwilliams** [comment]
Great - glad it's sorted!

Thanks! I'd be really interested to hear how you get on.

I've been considering trying to put together a classroom kit, so I'd love to know what kind of things you find work well and what kind of things don't.

> I think I found the docs

Did you post on the wrong GitHub issue?

**Comment by davidmoshal** [comment]
Great, we should collaborate - I teach a class of elementary school kids (I'm the 'Maker dad').
ping me: dmoshal at gmail.

re: the docs, yes, was multi-tasking, meant to reply to nkolban on another issue.

**Comment by aaronpowell** [comment]
for what it's worth - working fine on Node.js v4.x under Windows here :smile:

**Comment by gfwilliams** [comment]
Working fine on node 4 and 6
