### ISSUE TITLE
Dependency "tar.gz" is deprecated and contains security vulnerabilities

### ISSUE THREAD

**Issue by slank** [espruino/EspruinoTools#155]
Direct dependency "tar.gz" is deprecated and shouldn't be used any more. As far as I can tell it's not directly used within the project, plus there is an independent tar/gz implementation in `lib/targz.js`. Removing this dependency will satisfy npm's audit warnings about critical bugs in the package.

**Comment by gfwilliams** [comment]
Thanks!
