### ISSUE TITLE
Use CLI with IDE Relay?

### ISSUE THREAD

**Issue by jamesogrant** [espruino/EspruinoTools#160]
Hi Gordon,

Is it possible to use the CLI with the [IDE Relay](https://www.espruino.com/ide/relay/)?

Thanks!

**Comment by gfwilliams** [comment]
There wasn't, but I just added it! It'd make a huge difference on systems where Bluetooth LE support on Node.js isn't that great. 

Info on usage is in the README.

Personally I'd like to get something better working with peer.js so it's not going through my server, and ideally with the option of streaming webcam video - there are a bunch of cases where it'd be handy to be able to remotely help people out.
