### ISSUE TITLE
Serial port implementation is not returning ArrayBuffers

### ISSUE THREAD

**Issue by davidmoshal** [espruino/EspruinoTools#18]
Receiving this error intermittently, seems to occur while typing a command:  
`Serial port implementation is not returning ArrayBuffers`

Running espruino like this:
`espruino -p /dev/cu.usbmodem1411`

Is the problem in the `serial.js` file?

Dave

**Comment by gfwilliams** [comment]
Strange. It'll be a problem in [serial_nodeserial.js](https://github.com/espruino/EspruinoTools/blob/gh-pages/core/serial_nodeserial.js)

But having said that I don't see how it could possibly be doing that, as the code definitely does return an ArrayBuffer:

https://github.com/espruino/EspruinoTools/blob/gh-pages/core/serial_nodeserial.js#L33

Don't know if you have any thoughts on it? I guess node-serialport could be calling the callback with 0 bytes, or maybe on your version of node the `x instanceof ArrayBuffer` check doesn't work somehow.

**Comment by davidmoshal** [comment]
I cloned the repo and instrumented line 93 of the file `EspruinoTools/core/serial.js` as follows:
```
      // RECEIEVE DATA
      if (!(data instanceof ArrayBuffer)) console.warn("Serial port implementation is not returning ArrayBuffers, instead data=" + data + ", of type:" + (typeof data));
``` 

I ran the command: `bin/espruino-cli.js -p /dev/cu.usbmodem1421 -v`
and got this error:

`Serial port implementation is not returning ArrayBuffers, instead data=undefined, of type:undefined`

Dave

**Comment by davidmoshal** [comment]
Initially commands work fine, the suddenly any keypress results in undefined data. i.e, given this change:
```
      if(data){
         if (!(data instanceof ArrayBuffer))
           console.warn("Serial port implementation is not returning ArrayBuffers");
         if (readListener) readListener(data);
      } else {
        console.log("no data")
      }
```
The result after a few commands is that each keypress sends undefined data, like this:
```
no data
no data
no data
no data
```
This happens even with commands that don't throw errors.

**Comment by davidmoshal** [comment]
BTW - how are you running `espruino-cli.js` from inside the project?
I tried this without success: `node bin/espruino-cli.js -p /dev/cu.usbmodem1421 -v` 
It throws up all sorts of errors on connection.

**Comment by davidmoshal** [comment]
Console trace, i.e:
`if(!data) console.trace()`

results in:
```
Trace
    at currentDevice.open.currentDevice (eval at loadJS (/Users/davem/Documents/github-projects/EspruinoTools/index.js:9:15), <anonymous>:93:25)
    at SerialPort.eval (eval at loadJS (/Users/davem/Documents/github-projects/EspruinoTools/index.js:9:15), <anonymous>:33:9)
    at emitOne (events.js:77:13)
    at SerialPort.emit (events.js:169:7)
    at Object.module.exports.raw [as parser] (/Users/davem/Documents/github-projects/EspruinoTools/node_modules/serialport/parsers.js:8:13)
    at Object.SerialPort.opts.dataCallback (/Users/davem/Documents/github-projects/EspruinoTools/node_modules/serialport/serialport.js:181:12)
    at SerialPortFactory.SerialPort._emitData (/Users/davem/Documents/github-projects/EspruinoTools/node_modules/serialport/serialport.js:396:20)
    at afterRead (/Users/davem/Documents/github-projects/EspruinoTools/node_modules/serialport/serialport.js:372:20)
    at /Users/davem/Documents/github-projects/EspruinoTools/node_modules/serialport/serialport.js:388:9
    at FSReqWrap.wrapper [as oncomplete] (fs.js:614:17)
Serial port implementation is not returning ArrayBuffers, instead data=undefined, of type:undefined
```

and `serialport.js:388` is:
`afterRead(err, bytesRead, readPool, bytesRequested);`
which occurs in a block which starts:
`  if (process.platform !== 'win32') {`
 So that might be why you're not seeing it (I'm on a Mac).

Dave

**Comment by gfwilliams** [comment]
I use exactly what you did, and it works for me. I'm on Linux:

```
node bin/espruino-cli.js -p /dev/cu.usbmodem1421 -v 
```

Please can you instrument here?

https://github.com/espruino/EspruinoTools/blob/gh-pages/core/serial_nodeserial.js#L33

I'm struggling to see how it can ever call the callback with undefined. Even if you create a Uint8Array of length 0, there still appears to be a `buffer` member in it that is not undefined.

**Comment by gfwilliams** [comment]
Sorry - accidental close. I'm half asleep today.

It'd be good if you have an update though

**Comment by gfwilliams** [comment]
Pretty sure this is gone now
