### ISSUE TITLE
Use jsdom rather than node-jsdom

### ISSUE THREAD

**Issue by aaronpowell** [espruino/EspruinoTools#19]
I noticed that the tools depend on `node-jsdom` not `jsdom` and I'm guessing that the reason was because `jsdom` chased `io.js`. Given that they have converged I don't see any need for `node-jsdom` to be used and that the original can be swapped back in.

In my (simple) testing it seems to work just fine, although I haven't tried from the WebIDE, only the cli tools.

The reason that I'd like to see it switch back to just `jsdom` is that `node-jsdom` depends on `contextify` which is a real pain to get working smoothly on Windows, but has now been merged into node.js core so isn't required.

**Comment by gfwilliams** [comment]
The problem is that while it works for new Node.js, in my quick testing on 0.10/0.12, it didn't seem to work at all. I could be wrong about this but I think their chasing io.js might have meant that it wasn't compatible with a whole series of Node.js versions inbetween :(

Ideally I'd actually change the EspruinoTools code such that it didn't use jsdom or jquery at all. About the only thing that's used is `$.get`-style commands I think.

**Comment by aaronpowell** [comment]
Sure, it does mean any Node.js version pre v4.x isn't supported but I do wonder how big an impact that'd have, I believe v0.10 is not supported and at the end of year v0.12 will enter maintenance mode ([see here](https://nodejs.org/en/blog/release/v0.12.8/)).

Given that v4.0.0 was released 3 months ago [today](https://nodejs.org/en/blog/release/v4.0.0/) and is the current LTS version I don't see it as unrealistic a requirement (it also means that internally the code can use some ES6 features :wink:).

Anyway, my motivations are from the perspective of Windows devs who find that contextify can be an utter nightmare to try and get installed, compiled and working :stuck_out_tongue:

**Comment by gfwilliams** [comment]
> but I do wonder how big an impact that'd have

Most versions of Linux that users type `apt-get install` on? Raspberry Pi is quite a big one too, and I'm not sure which Node version is available for that.

It's a shame Linux seems so far behind, but a lot of people do use it and Ubuntu 14.04 LTS still uses 0.10. There's also `nw.js`, and that seems to use 0.12 - at least when I tried a few weeks back.

Honestly the best way forward it to get rid of the `jsdom`/`jquery` dependency completely - it pulls in so much extra stuff that's not needed, which makes it a pain to install on any platform.

**Comment by aaronpowell** [comment]
I didn't realise Linux distros could be so far behind, that's a shame (it's been a long time since I was running Linux).

I agree that removing the dependency on `jsdom`/`jQuery` would be ideal but I wonder if that's not harder than expected, with `$.<something>` used in a bunch of the core and plugin files (especially module loading).

Maybe a simple (yet dodgy) hack would be to check `process.version` and if the major version is >= `4` use `jsdom`, else use `node-jsdom`. Basically do:

```js
global.env = (process.version.startsWith('v0') ? require('node-jsdom') : require('jsdom')).env;
```

Sure you'd have to depend on _both_ in the `package.json` but that's not _that_ big a deal.

**Comment by gfwilliams** [comment]
Actually I just managed to rip out jquery and jsdom. Not actually too painful: https://github.com/espruino/EspruinoTools/commit/f2ae108e4e1193ddab5878e5229dd7d156f29a84

**Comment by aaronpowell** [comment]
I'll update my project to give this a crack :grinning:
