### ISSUE TITLE
Add Chrome App -> Web Bluetooth polyfill

### ISSUE THREAD

**Issue by gfwilliams** [espruino/EspruinoTools#20]
Here: https://github.com/WebBluetoothCG/chrome-app-polyfill

It would mean that the existing Web IDE app could use BLE on most chromebooks.

**Comment by beaufortfrancois** [comment]
Not relevant anymore I guess.

**Comment by gfwilliams** [comment]
Should Web Bluetooth 'just work' in the Chrome Web App, or do I need to request privileges for it?

Right now the file doesn't seem to be included, but it'd be relatively easy to add.

**Comment by beaufortfrancois** [comment]
Web Bluetooth works on Chrome Apps seamlessly. No special bluetooth permission in a manifest needed ;)

**Comment by gfwilliams** [comment]
Ok, great! What's the release date for that? My Chromebook is still on M51 by the look of it.

**Comment by beaufortfrancois** [comment]
According to https://www.chromium.org/developers/calendar, Chrome M53 will be around Sep 6th, 2016

**Comment by gfwilliams** [comment]
Done
