### ISSUE TITLE
same same, but different 

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoTools#23]
running two types of WebIDE with Chrome on MAC OS X , one from Chrome Web Store and the other as latest pull and unpacked from local folder.

![bildschirmfoto 2016-01-29 um 11 52 19](https://cloud.githubusercontent.com/assets/15932646/12673790/20d61e22-c67f-11e5-8231-065b26a803ed.JPG)

Web Store App can connect serial and network attached devices, unpacked not.

**Any idea how to investigate ?**

SETTINGS > CONSOLE 
>>> Connecting...
Set Slow Write = true
[object Object]
Connected [object Object]
Got ""
No Prompt found, got undefined - issuing Ctrl-C to try and break out
>>> Sending...
---> " \u0003echo(0);\nconsole.log(\"<\",\"<<\",JSON.stringify(process.env),\">>\",\">\");\n"
>>> Sent
WARNING: No result found - just got ""
Device found (connectionId=4)
>>> Connected to port /dev/cu.usbserial-A50285BI

**Comment by gfwilliams** [comment]
Are you sure you didn't just leave the other one connected to the same port? It all works here.

**Comment by MaBecker** [comment]
double checked - same result

running Chrome Version 46.0.2490.86 (64-bit) on MAC OS X 10.10.5

**Comment by gfwilliams** [comment]
Just checked on 2nd computer, and working fine here - so not sure what to suggest.

**Comment by MaBecker** [comment]
updated chrome on MAC OS : same, grrrrrrrrr  - Apples fault again :-1: 

Test on Windows VM : everything works  perfect :100: 

will try to debug ......

**Comment by MaBecker** [comment]
no my fault - wrong baud rate
