### ISSUE TITLE
Change minification method in espruino-cli.js to ESPRIMA

### ISSUE THREAD

**Issue by ssteidte** [espruino/EspruinoTools#30]
It is absolutely desirable to have minification, at least to strip the comments.
The current hard coded method for minification in the CLI is SIMPLE_OPTIMIZATIONS, which is not always working. ESPRIMA seems to be much more reliable.

**Comment by gfwilliams** [comment]
Ok, thanks - `SIMPLE_OPTIMIZATIONS` uses the Google online compiler, which is rate limited - so that could be your issue. I'll get that changed.

By the way: any comments that are *outside* or at the start of functions automatically get removed by Espruino.
