### ISSUE TITLE
Connect over TCP Address

### ISSUE THREAD

**Issue by Ti-webdev** [espruino/EspruinoTools#32]
Using Espruino Web IDE we can connect to ESP over TCP/IP address.
It will be useful here too.

**Comment by gfwilliams** [comment]
Thanks! Yes,  good idea!

**Comment by arknotts** [comment]
Would be great to have this as an option! This would let one script code updates to several espruinos over wifi, which could save a lot of time when there are a lot of them. I'm not familiar with the code much, but on first glance it seems that another TCP serial module could be added that isn't coupled to the chrome sockets library. I might try my hand at a PR at some point.

**Comment by gfwilliams** [comment]
Hi - yes, that'd be great!

Hopefully it wouldn't be too hard to copy serial_socket.js and make it work with Node's API. Then it's just a matter of making the command-line part of it set Espruino.Config.SERIAL_TCPIP and the port to the same IP address and you're sorted.

Out of interest, what boards are you using it with? ESP8266?

**Comment by arknotts** [comment]
@gfwilliams Yes I'm using pretty much all ESP8266's right now. Only one has espruino flashed on it (the rest have nodemcu/lua) but I'm planning on converting the rest over after trying it. I'd love to have my entire IoT codebase in JavaScript (going to try TypeScript on it as well) and being able to update so easily OTA is a big plus.

**Comment by planer-pro** [comment]
Very usable GREAT IDEA!

**Comment by gfwilliams** [comment]
done now
