### ISSUE TITLE
bleat alternatives?

### ISSUE THREAD

**Issue by chalkers** [espruino/EspruinoTools#38]
Will this be the thing people need to use for Puck.js on Windows?

`nobel` is a dependency for `bleat`

https://www.youtube.com/watch?v=mL9B8wuEdms

**Comment by gfwilliams** [comment]
Yeah, I could use noble directly, but does bleat actually cause any problems for anyone right now?

**Comment by chalkers** [comment]
I think noble is the problem, that's the dependency bleat requires for you to jump through those hoops.

**Comment by gfwilliams** [comment]
Yes, I'm sure it is - but I do need Noble for BLE. It's an optional depenency though, so if it can't be installed it's not s big deal unless you needed the BLE support.

Bleat is basically a wrapper around noble  - but I believe that at the time I was using it, there were different modules needed for different OSes. I believe at the moment it solely uses noble, so it could be skipped out - but I don't think it will solve any of the underlying problems as long as noble is there.

**Comment by gfwilliams** [comment]
noble's now used instead of bleat
