### ISSUE TITLE
Parsing from Acorn when uploading copy/pasted code via CLI

### ISSUE THREAD

**Issue by jsavage** [espruino/EspruinoTools#44]
The attached code generated a strange error when uploaded via CLI. Note that I had to rename from .js to .txt to attach here.

The error reported with this code was repeatable and as follows:

```
Connected
Acorn parse for plugins/compiler.js failed.<br/>Check the editor window for syntax errors
undefined:44
    utf8.encode(c).split('').forEach(function(c) {
    ^

ReferenceError: utf8 is not defined
    at escapeChar (eval at loadJS (/usr/lib/node_modules/espruino/index.js:10:10), <anonymous>:44:5)
.....(lfurther info deleted here)

```

This error was resolved by re-typing the code manually so my guess is some unexpected characters picked up when copy pasting from forum.

[temp.txt](https://github.com/espruino/EspruinoTools/files/663072/temp.txt)

**Comment by gfwilliams** [comment]
Thanks! I'll get that fixed.

However, chances are it will fail in some separate way - there's a dodgy 'breakable space' character in the code (annoyingly the forum seems to insert them sometimes). The Web IDE actually detects it when you paste code in and removes the characters, but if you're using some other editor it may not do that.

I'm not sure it's a good idea to get in the habit of materially changing raw files that are uploaded though.

Had you considered the Web IDE server? `sudo npm install 0g espruino-web-ide` then `espruino-server`.

You can then connect to the Pi remotely at `http://raspberrypi.local:8080` and get a full Web IDE that can use BLE

**Comment by jsavage** [comment]
I agree about not changing raw files.  How about improving the error msg
instead.?  A copy code function on then forum might also assist if that is
available off the shelf.
Tnx

**Comment by gfwilliams** [comment]
The error message should be a lot better now - Espruino itself will usually complain, pointing to the exact character in the string.

Unfortunately, if I had control of the forum I'd have fixed the dodgy character issue :)

Do you remember where you copied from? It's possible the guy that runs it might be able to do something about it
