### ISSUE TITLE
CLI seems to require puck address in lower case

### ISSUE THREAD

**Issue by jsavage** [espruino/EspruinoTools#45]
I realise now that this has caught me out a few times... Not sure if this is intentional or unintentional behaviour but suggest it would make it easier for beginners if the CLI could accept puck addresses in upper case to facilitate copy paste from scan tools some of which report in upper case. 

See below
```
pi@raspberrypi:~/puck $ espruino -p d1:b2:18:9f:88:ea
Espruino Command-line Tool 0.0.26
-----------------------------------

Connecting to 'd1:b2:18:9f:88:ea'
Connected
noble: unknown peripheral null connected!
>
Press Ctrl-C again to exit
>noble: unknown peripheral null connected!

pi@raspberrypi:~/puck $ espruino -p D1:B2:18:9F:88:EA
Espruino Command-line Tool 0.0.26
-----------------------------------

Connecting to 'D1:B2:18:9F:88:EA'
Port "D1:B2:18:9F:88:EA" not found
Unable to connect!
pi@raspberrypi:~/puck $ 

```

**Comment by jsavage** [comment]
I am not sure what the noble error about null connected means either?

**Comment by gfwilliams** [comment]
Thanks - yes, that shouldn't be too painful to fix.

I'm not sure about the 'noble' error either - that seems to be some internal issue in the Bluetooth libraries... and it's odd because I haven't had it with a Pi here... Which Pi are you using, and does it have a recent OS on it?

**Comment by jsavage** [comment]
Here I am using a RaspberryPi V3 running a recently updated version of Jessie. That said, the node setup on this Pi had previously been node v6 when used for non-espruino purposes and I could well have broken something during my install of node v7 and install of espruino.  This particular puck was unused except for having the firmware update to 1.89.

**Comment by joshfarrant** [comment]
Apologies for jumping on this (slightly unrelated) issue, but I'm not having much luck elsewhere.

@jsavage Where are you finding your Puck's MAC address? Feel like I've looked everywhere and having no joy...

**Comment by jsavage** [comment]
Its not a mac address but its the name they come with.  You will see it
when interacting with a puck.js using the Espruino CLI from a raspberry pi.
I forget what came of this but I seem to recall that it seemed like a
constraint that should be relaxed or documented so that newbies did not get
caught out.
