### ISSUE TITLE
FTDI Name conflict with port validation

### ISSUE THREAD

**Issue by TrevorJTClarke** [espruino/EspruinoTools#59]
I came across a strange issue that blocks me from uploading to an Adafruit Huzzah breakout (ESP8266) via FTDI.

FTDI Name: `/dev/tty.usbserial-A103QO50`

The port flag is validating with: `next.indexOf("-")`

Solution would be to allow '-', but not allow flags. I have fixed this locally by changing to:
`next.substring(0,1) !== '-'`. I am not certain this will work in all scenarios, but it is allowing my FTDI to communicate properly. 

See: https://github.com/espruino/EspruinoTools/blob/gh-pages/bin/espruino-cli.js#L17

As noted, I have it working locally, and will send a PR for review shortly.
Cheers!

**Comment by gfwilliams** [comment]
Thanks! Yeah, that's nasty. In fact due to that same code in other places it would have been impossible to execute any expression containing `-`!
