### ISSUE TITLE
Esprima minification corrupts some lambdas

### ISSUE THREAD

**Issue by opichals** [espruino/EspruinoTools#64]
Please have a look at the https://github.com/espruino/EspruinoDocs/pull/353/commits/25dc728c9c98709dbb6005ae70650c85bad8bb38 MPR121 sensor module commit for the workarounds (removed the use of lambdas in favor of functions) that had to be made for the module to get minified correctly.

**Comment by gfwilliams** [comment]
Do you have an example of what way they got corrupted? I can't put minification into ES6 mode because Espruino doesn't support the full ES6 spec and the output would almost certainly contain code that Espruino couldn't execute. I guess that might affect the type of code that minification can accept?

If so, this might just be something we have to live with.

**Comment by opichals** [comment]
I think it works when the exports.connect is lambda, but the arguments are not minified at all.

When the MPR.setThresholds or MPR.touched is lambda the module gets truncated strangely so that it is not functional.

Do we know what are we missing from ES6 that could confuse the minifier? It could be a good idea to complete the Espruinos' ES6 support to whatever level is necessary.

**Comment by opichals** [comment]
Same issue https://github.com/opichals/EspruinoDocs/commit/d859be35e2c595aeef9f3aa78b46b01c06956595

**Comment by gfwilliams** [comment]
I'm open to suggestions for workarounds. Sadly even Esprima (the tool used for offline minification in the Web IDE) doesn't see capable of handling them :(

**Comment by opichals** [comment]
I am not sure about all the requirements. The new kid on the block for ES6 minification appears to be https://github.com/babel/minify. It is quite slow compared to say Uglify, but it should be easy enough to create an Espruino related Babel minify plugin stew.

**Comment by opichals** [comment]
The closure compiler is reported to work in node as well as in the browsers so once the EspruinoTools lib packaging is resolved it should just be fine. See my [experiment working in node.js](https://github.com/espruino/EspruinoTools/compare/gh-pages...opichals:use-built-in-closure-compiler-js?expand=1).

This could be a reasonable solution. Or am I missing something?

**Comment by gfwilliams** [comment]
There's the online closure minifier that should work then?

My problem is that while I could drag it into EspruinoTools, the chances of actually getting that running in the browser for the graphical IDE seem slim?

**Comment by opichals** [comment]
It should just work IMO. They use GTW which produces browser compatible JS output. I'll try to do a proper PR in this direction.

**Comment by opichals** [comment]
This should not be a problem as there is `terser` minification now available for offline minification.

**Comment by opichals** [comment]
The https://github.com/espruino/EspruinoTools/issues/58 (or https://github.com/espruino/Espruino/issues/1078) seems to be a duplicate of this.

@gfwilliams I'd suggest about deprecating the Esprima minifier in favor of `terser` as soon as the EspruinoTools get release.

**Comment by gfwilliams** [comment]
Closing this - Esprima fixed anyway with https://github.com/espruino/EspruinoTools/commit/a1493a2146455bc151da003113101a665bce0b50 - and yes, I will finally try and merge the rollup stuff too but there are PRs open for that :)
