### ISSUE TITLE
Unable to connect from command-line tool

### ISSUE THREAD

**Issue by ancienthero** [espruino/EspruinoTools#66]
Unable to connect from command-line tool, log here:
https://gist.github.com/ancienthero/1e6d2e66350f20a393d73c0caa3ffda4

**Comment by gfwilliams** [comment]
Closing this - nowhere near enough information, and also posted in the forums: http://forum.espruino.com/conversations/313561/

Given the extra info in the forum post, this is just a matter of the `serialport` module not installing correctly.

**Comment by gfwilliams** [comment]
Oops. actually it's unrelated to Espruino tools anyway - it's https://github.com/gzip/esp-cli/issues/2
