### ISSUE TITLE
Writing output file causes errors 

### ISSUE THREAD

**Issue by ancienthero** [espruino/EspruinoTools#67]
sending code with -o causes errors while without it works ok

```
➜  dcf-timer git:(master) ✗ espruino -m dcfTimeSwitchFlash.js -o out.js
Espruino Command-line Tool 0.0.35
-----------------------------------

Espruino.Core.Utils.getURL: got HTTP status code 404 for https://www.espruino.com/modules/Flash.min.js
Espruino.Core.Utils.getURL: got HTTP status code 404 for https://www.espruino.com/modules/Flash.js
Module Flash not found
Writing output to out.js
File written. Exiting.
➜  dcf-timer git:(master) ✗ espruino -m dcfTimeSwitchFlash.js          
Espruino Command-line Tool 0.0.35
-----------------------------------
Using first port, {"path":"/dev/cu.usbmodem15","usb":[1155,22336],"description":"Espruino board"}
Connecting to '/dev/cu.usbmodem15'
Connected
--] 
--]  _____                 _ 
--] |   __|___ ___ ___ _ _|_|___ ___ 
--] |   __|_ -| . |  _| | | |   | . |
--] |_____|___|  _|_| |___|_|_|_|___|
--]           |_| http://espruino.com
--]  1v94 Copyright 2016 G.Williams
--] 
--] >
--] =undefined
--] Erasing Flash.....
--] Writing...............................
--] Compressed 81600 bytes to 29444
```

**Comment by gfwilliams** [comment]
Yes, that's expected. If you do `-o` it's not connecting to your device, so it doesn't know what the device is, and has no idea what libraries are built in or not - you need to tell it which board you have.

When you don't specify `-o` *or* a port, as a convenience it connects to the first available serial device - which is what is happening in the second case,

There is an example of using `-o` at https://github.com/espruino/EspruinoTools#not-connecting

I guess we could add some message to say 'please specify a board type'?

**Comment by ancienthero** [comment]
Thank you for explanation. If I remember correctly this : `espruino -m filename.js -o out.js` worked in previous versions. An error message would be helpful
