### ISSUE TITLE
want to send 

### ISSUE THREAD

**Issue by Matthias-Hermsdorf** [espruino/EspruinoTools#84]
Hi,

if I send 
  
    socket.send({key:"value"});

to my espruino board and receive it there in a 

    ws.on('message',function(msg) {
         console.log("msg",msg, "typeof msg",typeof msg);
    });
 
I get 

    msg [object Object] string

So I have no access to the content. There is a bad toString() before it.
Perhaps, I thought, I should use the rawData Callback. But this is realy raw and not for me.

At the moment I go around this in writing only key:value and split(":") them afterwards. But it would be nice if JSON were possible.

**Comment by gfwilliams** [comment]
Please ask these questions on the forum: http://forum.espruino.com/

In this case it sounds like you just want `socket.send(JSON.stringify({key:"value"}))`
