### ISSUE TITLE
espruino --list shows no devices

### ISSUE THREAD

**Issue by iammikecohen** [espruino/EspruinoTools#85]
On my iMac when I run the list command my PuckJS is not found. Launching the Web IDE on the same machine shows the device. What am I doing wrong? I would love to drop the IDE and start coding from my normal IDE as soon as possible.

```
$ espruino --list
Espruino Command-line Tool 0.1.20
-----------------------------------

PORTS:
  /dev/cu.Bluetooth-Incoming-Port
```

<img width="1136" alt="screen shot 2018-11-24 at 2 48 49 pm" src="https://user-images.githubusercontent.com/12703795/48972816-31216480-eff8-11e8-951d-2bc7ed175a48.png">

**Comment by gfwilliams** [comment]
Try `espruino --list --verbose` and see if it says anything - most likely there was some error installing `noble` when you installed the command-line tools - `noble` is the library used to get Bluetooth LE support. You could try going into a temporary directory and typing `npm install noble` and seeing if it's able to succeed - if it fails that's definitely your issue.

If you have issues like this in future please can you ask on the forum though?

**Comment by gfwilliams** [comment]
Ok, #86 is fixed however it looks like Bluetooth LE is broken across the board on Node 10 so there's nothing I can do.

If you are on Node 10 then I'd suggest downgrading to Node 8 and everything should work fine.

**Comment by gfwilliams** [comment]
Closing this as no response
