### ISSUE TITLE
The serialport version used doesn't work in node 10.x and higher

### ISSUE THREAD

**Issue by opichals** [espruino/EspruinoTools#86]
It probably needs upgrading to a newer version to cope with the node's native module binding changes.

Also it would make sense to drop support for node 4.x+ as that is already in the [end-of-life stage](https://github.com/nodejs/Release#end-of-life-releases).

**Comment by gfwilliams** [comment]
Ok. just updated and  published.

Node 10 still appears to have broken noble via bluetooth-hci-socket though.
