### ISSUE TITLE
Connect over TCP Address

### ISSUE THREAD

**Issue by MaBecker** [espruino/EspruinoTools#94]
Is ist possible to connect over tcp/ip with espruino-commandline-tools like the ESPRUINO WEB IDE can do?

**Comment by gfwilliams** [comment]
Yes, you can: `--port tcp://192.168.1.50` - I've just updated the docs.

Please can you ask this sort of stuff on the forum in future though? I'm trying to keep GitHub for reproducible issues, not 'can I do X?' questions - otherwise it's hard for me to actually figure out what needs doing :)

**Comment by gfwilliams** [comment]
Just to add, this is why: https://github.com/espruino/EspruinoTools/issues/32

Closed bug, with literally the exact same title you typed: `Connect over TCP Address`

It's just that GitHub never seems to encourage people to look at closed bugs, so I just end up answering the same stuff over and over

**Comment by MaBecker** [comment]
Thanks, didn’t get that because it is not documented.

**Comment by MaBecker** [comment]
Thanks for adding it to the docs.
